# Generated by Django 5.1.1 on 2024-10-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('cost', models.IntegerField()),
                ('power', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
