# Generated by Django 5.1.1 on 2024-10-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0004_alter_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
