# Generated by Django 5.1.1 on 2024-10-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0005_alter_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='owned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(height_field=300, upload_to='card_images/', width_field=300),
        ),
    ]
