# Generated by Django 5.1.1 on 2024-10-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0006_card_owned_alter_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='card_images/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
