# Generated by Django 5.1.1 on 2024-11-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0008_alter_card_pool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='spotlights',
            field=models.ManyToManyField(to='snap.spotlight'),
        ),
    ]
