# Generated by Django 5.1.1 on 2024-11-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0010_remove_card_spotlights_spotlight_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotlight',
            name='cards',
        ),
        migrations.AddField(
            model_name='spotlight',
            name='card1',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spotlight',
            name='card2',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spotlight',
            name='card3',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spotlight',
            name='card4',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='spotlight',
            name='pulled1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spotlight',
            name='pulled2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spotlight',
            name='pulled3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spotlight',
            name='pulled4',
            field=models.BooleanField(default=False),
        ),
    ]
