# Generated by Django 5.1.1 on 2024-12-04 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0013_remove_spotlight_card1_remove_spotlight_card2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotlight',
            name='cards',
        ),
    ]
