# Generated by Django 5.1.1 on 2024-12-04 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0015_spotlight_card1_spotlight_card2_spotlight_card3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotlight',
            name='card1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_spotlight_slots', to='snap.card'),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='card2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_spotlight_slots', to='snap.card'),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='card3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_spotlight_slots', to='snap.card'),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='card4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fourth_spotlights_slots', to='snap.card'),
        ),
    ]
