# Generated by Django 5.1.1 on 2024-12-22 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0016_alter_spotlight_card1_alter_spotlight_card2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotlight',
            name='card4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fourth_spotlights_slots', to='snap.card'),
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('card1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_deck_slots', to='snap.card')),
                ('card10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenth_deck_slots', to='snap.card')),
                ('card11', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleventh_deck_slots', to='snap.card')),
                ('card12', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twelfth_deck_slots', to='snap.card')),
                ('card2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_deck_slots', to='snap.card')),
                ('card3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_deck_slots', to='snap.card')),
                ('card4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fourth_deck_slots', to='snap.card')),
                ('card5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fifth_deck_slots', to='snap.card')),
                ('card6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sixth_deck_slots', to='snap.card')),
                ('card7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seventh_deck_slots', to='snap.card')),
                ('card8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eighth_deck_slots', to='snap.card')),
                ('card9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ninth_deck_slots', to='snap.card')),
            ],
        ),
    ]
