# Generated by Django 5.1.1 on 2025-01-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0017_alter_spotlight_card4_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='released',
            field=models.BooleanField(default=True),
        ),
    ]
