# Generated by Django 5.1.1 on 2025-04-30 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0018_card_released'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_type', models.CharField(choices=[('seasonal_series_5', 'Seasonal Series 5'), ('seasonal_series_4', 'Seasonal Series 4'), ('collectors_series_5', "Collector's Series 5"), ('collectors_series_4', "Collector's Series 4"), ('collectors_series_3', "Collector's Series 3")], default='None', max_length=30)),
                ('date', models.DateField()),
                ('bonus1', models.CharField(choices=[('card', 'Card'), ('25_tokens', '25 Tokens'), ('50_tokens', '50 Tokens'), ('100_tokens', '100 Tokens'), ('1000_tokens', '1000 Tokens'), ('15_boosters', '15 Boosters'), ('35_boosters', '35 Boosters'), ('65_boosters', '65 Boosters'), ('155_boosters', '155 Boosters'), ('50_credits', '50 Credits'), ('100_credits', '100 Credits'), ('200_credits', '200 Credits'), ('1525_credits', '1525 Credits'), ('border', 'Border'), ('variant', 'Variant')], default='None', max_length=20)),
                ('bonus2', models.CharField(choices=[('card', 'Card'), ('25_tokens', '25 Tokens'), ('50_tokens', '50 Tokens'), ('100_tokens', '100 Tokens'), ('1000_tokens', '1000 Tokens'), ('15_boosters', '15 Boosters'), ('35_boosters', '35 Boosters'), ('65_boosters', '65 Boosters'), ('155_boosters', '155 Boosters'), ('50_credits', '50 Credits'), ('100_credits', '100 Credits'), ('200_credits', '200 Credits'), ('1525_credits', '1525 Credits'), ('border', 'Border'), ('variant', 'Variant')], default='None', max_length=20)),
                ('card1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_pack_slots', to='snap.card')),
                ('card2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_pack_slots', to='snap.card')),
                ('card3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_pack_slots', to='snap.card')),
            ],
        ),
    ]
