# Generated by Django 5.1.1 on 2025-04-30 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0019_pack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pack',
            old_name='card2',
            new_name='bonus_card1',
        ),
        migrations.RenameField(
            model_name='pack',
            old_name='card3',
            new_name='bonus_card2',
        ),
        migrations.RenameField(
            model_name='pack',
            old_name='card1',
            new_name='main_card',
        ),
    ]
